Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,10 +18,12 @@ script:
   - cat coverage/lcov.info || echo "lcov.info file not found"
   - if [ -f coverage/lcov.info ]; then
       echo "Coverage file found, uploading with bash uploader...";
-      curl -s https://codecov.io/bash | bash -s -- -f coverage/lcov.info || echo "Codecov upload failed";
+      curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f coverage/lcov.info || echo "Codecov upload failed";
     else
       echo "Coverage file missing, skipping upload.";
       exit 1;
     fi
+
+
 
 
